version: '3.8'

services:
  hasu-no-sora:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HTTP_PROXY=http://127.0.0.1:7890
        - HTTPS_PROXY=http://127.0.0.1:7890
        - NO_PROXY=localhost,127.0.0.1
    container_name: hasu-no-sora-player
    ports:
      - "3000:3000"
    volumes:
      - ./music:/app/music:ro
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hasu-no-sora.rule=Host(`localhost`)"
      - "traefik.http.services.hasu-no-sora.loadbalancer.server.port=3000"

networks:
  default:
    name: hasu-no-sora-network
